spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3308/ottsharing?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER # Spring boot 2.6버전 이후부터 발생하는 Swagger3.0.0 충돌 문제 해결하기 위한 설정
    hiddenmethod:
      filter:
        enabled: true
  mail:
    host: smtp.gmail.com
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
    port: 587
    properties:
      mail.smtp:
        auth: true
        timeout: 5000
        starttls:
          enable: true

ottsharing:
  serviceFee: 5000
app:
  mail:
    host: http://localhost:8080
mybatis:
  mapper-locations: mapper/*xml
