spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3308/ottsharing?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 4869
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER # Spring boot 2.6버전 이후부터 발생하는 Swagger3.0.0 충돌 문제 해결하기 위한 설정
    hiddenmethod:
      filter:
        enabled: true

ottsharing:
  serviceFee: 5000
